INSERT INTO `tl_liens` (`lien_url`, `lien_titre`, `lien_desc`, `user_id`) VALUES
('https://developer.mozilla.org/', 'MDN Web Docs', 'Documentation complète pour HTML, CSS, JavaScript et plus.', 1),
('https://css-tricks.com/', 'CSS-Tricks', 'Astuces, articles et guides sur le CSS et le web design.', 1),
('https://stackoverflow.com/', 'Stack Overflow', 'Communauté de questions/réponses pour développeurs.', 1),
('https://github.com/', 'GitHub', 'Plateforme d’hébergement et de gestion de code source.', 1),
('https://codepen.io/', 'CodePen', 'Environnement de développement front-end en ligne.', 1),
('https://freecodecamp.org/', 'freeCodeCamp', 'Apprendre à coder gratuitement avec des projets pratiques.', 1),
('https://www.w3schools.com/', 'W3Schools', 'Tutoriels et références pour les technologies web.', 1),
('https://www.smashingmagazine.com/', 'Smashing Magazine', 'Articles et ressources pour designers et développeurs web.', 1),
('https://www.tutorialspoint.com/', 'TutorialsPoint', 'Tutoriels sur de nombreux langages et frameworks.', 1),
('https://www.codecademy.com/', 'Codecademy', 'Plateforme interactive pour apprendre à coder.', 1),
('https://www.udemy.com/', 'Udemy', 'Cours en ligne sur le développement web et plus.', 1),
('https://www.coursera.org/', 'Coursera', 'Cours universitaires en ligne, y compris le développement web.', 1),
('https://www.pluralsight.com/', 'Pluralsight', 'Formations techniques pour développeurs.', 1),
('https://www.sitepoint.com/', 'SitePoint', 'Ressources et livres pour développeurs web.', 1),
('https://www.hackerrank.com/', 'HackerRank', 'Plateforme de pratique de code et de défis.', 1),
('https://www.frontendmentor.io/', 'Frontend Mentor', 'Défis de développement front-end réels.', 1),
('https://www.javascript.com/', 'JavaScript.com', 'Ressources et guides pour JavaScript.', 1),
('https://reactjs.org/', 'React', 'Documentation officielle de la bibliothèque React.', 1),
('https://vuejs.org/', 'Vue.js', 'Documentation officielle du framework Vue.js.', 1),
('https://angular.io/', 'Angular', 'Documentation officielle du framework Angular.', 1),
('https://getbootstrap.com/', 'Bootstrap', 'Framework CSS populaire pour le développement responsive.', 1),
('https://tailwindcss.com/', 'Tailwind CSS', 'Framework CSS utilitaire moderne.', 1),
('https://sass-lang.com/', 'Sass', 'Langage de préprocesseur CSS.', 1),
('https://webpack.js.org/', 'Webpack', 'Module bundler pour JavaScript.', 1),
('https://nodejs.org/', 'Node.js', 'Environnement d’exécution JavaScript côté serveur.', 1),
('https://expressjs.com/', 'Express', 'Framework web minimaliste pour Node.js.', 1),
('https://laravel.com/', 'Laravel', 'Framework PHP moderne pour le développement web.', 1),
('https://symfony.com/', 'Symfony', 'Framework PHP robuste et modulaire.', 1),
('https://www.php.net/', 'PHP', 'Site officiel du langage PHP.', 1),
('https://mysql.com/', 'MySQL', 'Système de gestion de base de données open source.', 1);